default: paper

paper: trapping.tex
	pdflatex trapping
	pdflatex trapping
	open trapping.pdf

nonaxi: nonaxi.tex
	pdflatex nonaxi
	pdflatex nonaxi
	open nonaxi.pdf

clean:
	rm -f *.log *.aux *.dvi *.ps *.pdf
